GuarantyWeb/Areas/PonziAdmin/Controllers/TransactionSplitController.cs
using PonziBussinessLogic.Implementation;
using PonziRepostiory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuarantyWeb.Areas.PonziAdmin.Controllers
{
    public class TransactionSplitController : Controller
    {
        PonziAdminLogin Context = new PonziAdminLogin();
        // GET: PonziAdmin/TransactionSplit
        public ActionResult Index()
        {
            try
            {
                ViewBag.msg = "";
                ViewBag.trans = new SelectList(Context.GetAllTransactions().Result, "Id", "Description");
            //    var det = Context.GetAllTransactionSplit((int)trans);

                return View();

            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Index(int trans)
        {
            try
            {
                var det = Context.GetAllTransactionSplit(trans);
                ViewBag.trans = new SelectList(Context.GetAllTransactions().Result, "Id", "Description",trans);
                return View(det.Result);
            }
            catch
            {
                return View();
            }
        }
        // GET: PonziAdmin/TransactionSplit/Details/5
        public ActionResult Details(int id)
        {
            var msg = Context.GetSingleTransactionSplit(id);
            return View(msg.Result);
        }

        // GET: PonziAdmin/TransactionSplit/Create
        public ActionResult Create()
        {
            ViewBag.trans = new SelectList(Context.GetAllTransactions().Result, "Id", "Description");
            return View();
        }

        // POST: PonziAdmin/TransactionSplit/Create
        [HttpPost]
        public ActionResult Create(TransactionSplit transSplit)
        {
            try
            {
            
                var msg= Context.CreateNewTransactionSplit(transSplit);
                ViewBag.trans = new SelectList(Context.GetAllTransactions().Result, "Id", "Description", transSplit.TransId);

                if (msg.Result == false)
                {
                    ViewBag.msg = msg.Message;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: PonziAdmin/TransactionSplit/Edit/5
        public ActionResult Edit(int id)
        {

            ViewBag.trans = new SelectList(Context.GetAllTransactions().Result, "Id", "Description");
            var msg = Context.GetSingleTransactionSplit(id);
            return View(msg.Result);
        }

        // POST: PonziAdmin/TransactionSplit/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TransactionSplit trans)
        {
            try
            {
                // TODO: Add update logic here
                var msg = Context.EditTransactionSplit(trans);
                ViewBag.trans = new SelectList(Context.GetAllTransactions().Result, "Id", "Description",trans.TransId);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: PonziAdmin/TransactionSplit/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PonziAdmin/TransactionSplit/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GuarantyWeb/Areas/PonziAdmin/Views/TransactionSplit/Create.cshtml
@model PonziRepostiory.TransactionSplit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction Split</h4>
        <hr />
        <p>@ViewBag.msg</p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SplitDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SplitDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SplitDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SplitPercentage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SplitPercentage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SplitPercentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TransId", ViewBag.trans as SelectList, htmlAttributes: new  { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TransId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsFirst, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsFirst)
                    @Html.ValidationMessageFor(model => model.IsFirst, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaturityTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaturityTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaturityTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GuarantyWeb/Areas/PonziAdmin/Views/TransactionSplit/Details.cshtml
@model PonziRepostiory.TransactionSplit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TransactionSplit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SplitDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SplitDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SplitPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SplitPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsFirst)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsFirst)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaturityTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaturityTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GuarantyWeb/Areas/PonziAdmin/Views/TransactionSplit/Edit.cshtml
@model PonziRepostiory.TransactionSplit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TransactionSplit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SplitDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SplitDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SplitDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SplitPercentage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SplitPercentage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SplitPercentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TransId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsFirst, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsFirst)
                    @Html.ValidationMessageFor(model => model.IsFirst, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaturityTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaturityTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaturityTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GuarantyWeb/Areas/PonziAdmin/Views/TransactionSplit/Index.cshtml
@model IEnumerable<PonziRepostiory.TransactionSplit>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index","TransactionSplit",FormMethod.Post))
{
<p><b>Transaction Detail</b>@Html.DropDownList("trans", ViewBag.trans as SelectList, htmlAttributes: new { @class = "form-control" })
   <input type="submit" value="submit"/>
     </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SplitDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SplitPercentage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsFirst)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaturityTime)
        </th>
        <th></th>
    </tr>

@if(Model!=null)
{
    foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SplitDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SplitPercentage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsFirst)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaturityTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }
}

</table>